name: Build Client176 DLL

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build solution (Release x86)
      run: |
        msbuild /m /p:Configuration=Release /p:Platform=x86 /p:OutDir=.\output\ *.sln

    - name: Upload DLL artifact
      uses: actions/upload-artifact@v4
      with:
        name: ijl15.dll
        path: output/ijl15.dll
